"""initial schema

Revision ID: 89398913f6cb
Revises:
Create Date: 2026-09-14 23:02:18.036169

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89398913f6cb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "webhook_type",
            sa.Enum("NONE", "TEAMS", "SLACK", "DISCORD", name="webhooktype"),
            nullable=False,
        ),
        sa.Column("webhook_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("next_ticket_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_project_slug"), ["slug"], unique=True)

    op.create_table(
        "user",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

    op.create_table(
        "project_member",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sa.Enum("OWNER", "MEMBER", name="role"), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "user_id", name="uq_member_project_user"),
    )
    with op.batch_alter_table("project_member", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_member_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_project_member_user_id"), ["user_id"], unique=False)

    op.create_table(
        "ticket",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ticket_number", sa.Integer(), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=20000), nullable=False),
        sa.Column(
            "type",
            sa.Enum("STORY", "BUG", "DEMO_REQUEST", "TASK", name="tickettype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("BACKLOG", "SELECTED", "IN_PROGRESS", "DONE", name="ticketstatus"),
            nullable=False,
        ),
        sa.Column(
            "priority", sa.Enum("LOW", "MEDIUM", "HIGH", "URGENT", name="priority"), nullable=False
        ),
        sa.Column("story_points", sa.Integer(), nullable=True),
        sa.Column("creator_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("assignee_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resolution_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "ticket_number", name="uq_ticket_project_number"),
    )
    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ticket_assignee_id"), ["assignee_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ticket_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ticket_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ticket_ticket_number"), ["ticket_number"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ticket_ticket_number"))
        batch_op.drop_index(batch_op.f("ix_ticket_status"))
        batch_op.drop_index(batch_op.f("ix_ticket_project_id"))
        batch_op.drop_index(batch_op.f("ix_ticket_assignee_id"))

    op.drop_table("ticket")
    with op.batch_alter_table("project_member", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_member_user_id"))
        batch_op.drop_index(batch_op.f("ix_project_member_project_id"))

    op.drop_table("project_member")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_slug"))

    op.drop_table("project")
    # ### end Alembic commands ###
